Changes for PowerAPI monitoring

diff --git a/.github/workflows/maven-build-docker-image.yml b/.github/workflows/maven-build-docker-image.yml
--- a/.github/workflows/maven-build-docker-image.yml
+++ b/.github/workflows/maven-build-docker-image.yml
@@ -1,290 +1,206 @@
-name: Maven Build Docker Image
-on:
-  workflow_call:
-    inputs:
-      ref:
-        description: 'Ref to checkout'
-        required: true
-        type: string
-      docker_platforms:
-        description: 'Docker platforms to build the image on'
-        required: false
-        type: string
-        default: 'linux/amd64'
-      docker_context_cache_key:
-        description: 'Cache key for the docker context'
-        required: false
-        type: string
-      docker_registry:
-        description: 'Docker registry to push the image to (DOCKER.IO, GHCR.IO, BOTH)'
-        required: false
-        type: string
-        default: 'DOCKER.IO'
-      force_snapshot:
-        description: 'Force snapshot'
-        required: false
-        type: boolean
-        default: false
-    secrets:
-      docker_io_username:
-        description: 'Docker.io username'
-        required: false
-      docker_io_token:
-        description: 'Docker.io token'
-        required: false
-      ghcr_io_username:
-        description: 'GHCR.io username'
-        required: false
-      ghcr_io_token:
-        description: 'GHCR.io token'
-        required: false
-    outputs:
-      tags:
-        value: ${{ jobs.build-push-image.outputs.tags }}
-      version:
-        value: ${{ jobs.build-push-image.outputs.version }}
-      formatted_tags:
-        value: ${{ jobs.build-push-image.outputs.formatted_tags }}
 jobs:
   build-push-image:
-    name: Build/Push Image
-    runs-on: ubuntu-latest
     env:
-      JAVA_VERSION: 11
-      JAVA_DISTRO: temurin
-      JVM_TEST_MAVEN_OPTS: '-e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
       DOCKER_BUILD_CONTEXT: /home/runner/work/_temp/core-build
-    outputs:
-      tags: ${{ steps.meta.outputs.tags }}
-      formatted_tags: ${{ steps.format-tags.outputs.formatted_tags }}
-      version: ${{ steps.set-common-vars.outputs.version }}
+      JAVA_DISTRO: temurin
+      JAVA_VERSION: 11
+      JVM_TEST_MAVEN_OPTS: -e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
     if: success()
+    name: Build/Push Image
+    outputs:
+      formatted_tags: ${{ steps.format-tags.outputs.formatted_tags }}
+      tags: ${{ steps.meta.outputs.tags }}
+      version: ${{ steps.set-common-vars.outputs.version }}
+    runs-on: self-hosted
     steps:
-      - run: echo 'GitHub context'
-        env:
-          GITHUB_CONTEXT: ${{ toJson(github) }}
+    - continue-on-error: true
+      env:
+        GITHUB_CONTEXT: ${{ toJson(github) }}
+      run: echo 'GitHub context'
+    - continue-on-error: true
+      name: Checkout core
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ inputs.ref }}
+    - continue-on-error: true
+      name: Cleanup
+      uses: ./.github/actions/cleanup-runner
+    - continue-on-error: true
+      id: restore-docker-context
+      if: inputs.docker_context_cache_key != ''
+      name: Restore Docker Context
+      uses: actions/cache/restore@v3
+      with:
+        key: ${{ inputs.docker_context_cache_key }}
+        path: ${{ env.DOCKER_BUILD_CONTEXT }}/context
+    - continue-on-error: true
+      id: build-status
+      name: Build Status
+      run: "rebuild=false\nif [[ -z \"${{ inputs.docker_context_cache_key }}\" ||\
+        \ ! -d ${DOCKER_BUILD_CONTEXT}/context ]]; then\n  rebuild=true\nfi\n\necho\
+        \ \"rebuild=${rebuild}\" >> $GITHUB_OUTPUT\n"
+    - continue-on-error: true
+      if: steps.build-status.outputs.rebuild == 'true'
+      name: Setup Java
+      uses: actions/setup-java@v3
+      with:
+        distribution: ${{ env.JAVA_DISTRO }}
+        java-version: ${{ env.JAVA_VERSION }}
+    - continue-on-error: true
+      if: steps.build-status.outputs.rebuild == 'true'
+      name: Build Core
+      run: "mkdir -p ${DOCKER_BUILD_CONTEXT}/context\n./mvnw -ntp \\\n  ${JVM_TEST_MAVEN_OPTS}\
+        \ \\\n  -Dprod=true \\\n  -Ddocker.buildArchiveOnly=${DOCKER_BUILD_CONTEXT}\
+        \ \\\n  -DskipTests=true \\\n  -DskipITs=true \\\n  clean install \\\n  --file\
+        \ pom.xml \\\n  --show-version\nrc=$?\nif [[ $rc != 0 ]]; then\n  echo \"\
+        Build failed with exit code $rc\"\n  exit $rc\nfi\n"
+    - continue-on-error: true
+      id: setup-docker-context
+      if: success() && steps.build-status.outputs.rebuild == 'true'
+      name: Setup Context
+      run: 'mkdir -p ${DOCKER_BUILD_CONTEXT}/context
 
-      - name: Checkout core
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.ref }}
+        tar -xvf ${DOCKER_BUILD_CONTEXT}/docker-build.tar -C ${DOCKER_BUILD_CONTEXT}/context
 
-      - name: Cleanup
-        uses: ./.github/actions/cleanup-runner
+        '
+    - continue-on-error: true
+      id: set-common-vars
+      if: success()
+      name: Set Common Vars
+      run: "build_properties_path=${DOCKER_BUILD_CONTEXT}/context/maven/dotserver/tomcat-*/webapps/ROOT/WEB-INF/classes/build.properties\n\
+        build_properties=''\nif ! ls ${build_properties_path} 1> /dev/null 2>&1; then\n\
+        \  echo 'Could not find build.properties, aborting'\n  exit 1\nelse\n  build_properties=$(eval\
+        \ find \"$build_properties_path\" -print)\nfi\n\necho 'Build properties:'\n\
+        cat ${build_properties}\n\nversion=$(cat ${build_properties} | grep version\
+        \ | cut -d'=' -f2)\nbuild_hash=$(cat ${build_properties} | grep revision |\
+        \ cut -d'=' -f2)\nif [[ ! ${build_hash} =~ ^[0-9a-f]{7}$ ]]; then\n  build_hash=$(git\
+        \ log -1 --pretty=%h)\n  build_hash=${build_hash::7}\nfi\n\nbuild_id=${{ inputs.ref\
+        \ }}\nis_trunk=false\nif [[ \"${build_id}\" == 'master' || ${build_id} =~\
+        \ ^v[0-9]{2}.[0-9]{2}.[0-9]{2}_lts$ ]]; then\n  is_trunk=true\nfi\n\nis_lts=false\n\
+        if [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts(_v[0-9]{2})?$ ]]; then\n\
+        \  is_lts=true\nfi\n\nis_snapshot=false\nis_release=false\nis_latest=false\n\
+        is_custom=false\nis_trunk_snapshot=false\n\nif [[ ${version} =~ ^[0-9]{1}.[0-9]{1}.[0-9]{1}-SNAPSHOT$\
+        \ ]]; then\n  version=${build_id}\n  is_snapshot=true\n  if [[ \"${is_trunk}\"\
+        \ == 'true' ]]; then\n    is_trunk_snapshot=true\n  fi\nelif [[ ${version}\
+        \ =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}$ ]]; then\n  is_release=true\n  is_latest=true\n\
+        elif [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts$ ]]; then\n  is_snapshot=true\n\
+        \  version=${build_id}\nelif [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts_v[0-9]{2}$\
+        \ ]]; then\n  is_release=true\nelse\n  is_custom=true\n  version=${build_id}\n\
+        fi\n\nif [[ \"${{ inputs.force_snapshot }}\" == 'true' ]]; then\n  is_snapshot=true\n\
+        \  is_release=false\n  is_latest=false\nfi\n\necho \"version=${version}\"\n\
+        echo \"build_hash=${build_hash}\"\necho \"build_id=${build_id}\"\necho \"\
+        is_trunk=${is_trunk}\"\necho \"is_lts=${is_lts}\"\necho \"is_snapshot=${is_snapshot}\"\
+        \necho \"is_trunk_snapshot=${is_trunk_snapshot}\"\necho \"is_release=${is_release}\"\
+        \necho \"is_latest=${is_latest}\"\necho \"is_custom=${is_custom}\"\n\necho\
+        \ \"version=${version}\" >> $GITHUB_OUTPUT\necho \"build_hash=${build_hash}\"\
+        \ >> $GITHUB_OUTPUT\necho \"build_id=${build_id}\" >> $GITHUB_OUTPUT\necho\
+        \ \"is_trunk=${is_trunk}\" >> $GITHUB_OUTPUT\necho \"is_lts=${is_lts}\" >>\
+        \ $GITHUB_OUTPUT\necho \"is_snapshot=${is_snapshot}\" >> $GITHUB_OUTPUT\n\
+        echo \"is_trunk_snapshot=${is_trunk_snapshot}\" >> $GITHUB_OUTPUT\necho \"\
+        is_release=${is_release}\" >> $GITHUB_OUTPUT\necho \"is_latest=${is_latest}\"\
+        \ >> $GITHUB_OUTPUT\necho \"is_custom=${is_custom}\" >> $GITHUB_OUTPUT\n"
+    - continue-on-error: true
+      if: inputs.docker_registry == 'DOCKER.IO' || inputs.docker_registry == 'BOTH'
+      name: Docker.io login
+      uses: docker/login-action@v3.0.0
+      with:
+        password: ${{ secrets.docker_io_token }}
+        username: ${{ secrets.docker_io_username }}
+    - continue-on-error: true
+      if: inputs.docker_registry == 'GHCR.IO' || inputs.docker_registry == 'BOTH'
+      name: GHCR.io login
+      uses: docker/login-action@v3.0.0
+      with:
+        password: ${{ secrets.ghcr_io_token }}
+        registry: ghcr.io
+        username: ${{ secrets.ghcr_io_username }}
+    - continue-on-error: true
+      id: meta
+      if: success()
+      name: Docker Metadata
+      uses: docker/metadata-action@v5
+      with:
+        images: 'dotcms/dotcms
 
-      - name: Restore Docker Context
-        id: restore-docker-context
-        uses: actions/cache/restore@v3
-        with:
-          path: ${{ env.DOCKER_BUILD_CONTEXT }}/context
-          key: ${{ inputs.docker_context_cache_key }}
-        if: inputs.docker_context_cache_key != ''
+          '
+        tags: 'type=raw,value=${{ steps.set-common-vars.outputs.version }}_{{sha}},enable=true
 
-      - name: Build Status
-        id: build-status
-        run: |
-          rebuild=false
-          if [[ -z "${{ inputs.docker_context_cache_key }}" || ! -d ${DOCKER_BUILD_CONTEXT}/context ]]; then
-            rebuild=true
-          fi
-          
-          echo "rebuild=${rebuild}" >> $GITHUB_OUTPUT
+          type=raw,value=${{ steps.set-common-vars.outputs.version }}_SNAPSHOT,enable=${{
+          steps.set-common-vars.outputs.is_snapshot }}
 
-      - name: Setup Java
-        uses: actions/setup-java@v3
-        with:
-          java-version: ${{ env.JAVA_VERSION }}
-          distribution: ${{ env.JAVA_DISTRO }}
-        if: steps.build-status.outputs.rebuild == 'true'
+          type=raw,value=${{ steps.set-common-vars.outputs.version }}_latest_SNAPSHOT,enable=${{
+          steps.set-common-vars.outputs.is_trunk_snapshot }}
 
-      - name: Build Core
-        run: |
-          mkdir -p ${DOCKER_BUILD_CONTEXT}/context
-          ./mvnw -ntp \
-            ${JVM_TEST_MAVEN_OPTS} \
-            -Dprod=true \
-            -Ddocker.buildArchiveOnly=${DOCKER_BUILD_CONTEXT} \
-            -DskipTests=true \
-            -DskipITs=true \
-            clean install \
-            --file pom.xml \
-            --show-version
-          rc=$?
-          if [[ $rc != 0 ]]; then
-            echo "Build failed with exit code $rc"
-            exit $rc
-          fi
-        if: steps.build-status.outputs.rebuild == 'true'
+          type=raw,value=${{ steps.set-common-vars.outputs.version }},enable=${{ steps.set-common-vars.outputs.is_release
+          }}
 
-      - name: Setup Context
-        id: setup-docker-context
-        run: |
-          mkdir -p ${DOCKER_BUILD_CONTEXT}/context
-          tar -xvf ${DOCKER_BUILD_CONTEXT}/docker-build.tar -C ${DOCKER_BUILD_CONTEXT}/context
-        if: success() && steps.build-status.outputs.rebuild == 'true'
+          type=raw,value=latest,enable=${{ steps.set-common-vars.outputs.is_latest
+          }}
 
-      - name: Set Common Vars
-        id: set-common-vars
-        run: |
-          build_properties_path=${DOCKER_BUILD_CONTEXT}/context/maven/dotserver/tomcat-*/webapps/ROOT/WEB-INF/classes/build.properties
-          build_properties=''
-          if ! ls ${build_properties_path} 1> /dev/null 2>&1; then
-            echo 'Could not find build.properties, aborting'
-            exit 1
-          else
-            build_properties=$(eval find "$build_properties_path" -print)
-          fi
-          
-          echo 'Build properties:'
-          cat ${build_properties}
-          
-          version=$(cat ${build_properties} | grep version | cut -d'=' -f2)
-          build_hash=$(cat ${build_properties} | grep revision | cut -d'=' -f2)
-          if [[ ! ${build_hash} =~ ^[0-9a-f]{7}$ ]]; then
-            build_hash=$(git log -1 --pretty=%h)
-            build_hash=${build_hash::7}
-          fi
-          
-          build_id=${{ inputs.ref }}
-          is_trunk=false
-          if [[ "${build_id}" == 'master' || ${build_id} =~ ^v[0-9]{2}.[0-9]{2}.[0-9]{2}_lts$ ]]; then
-            is_trunk=true
-          fi
-          
-          is_lts=false
-          if [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts(_v[0-9]{2})?$ ]]; then
-            is_lts=true
-          fi
-          
-          is_snapshot=false
-          is_release=false
-          is_latest=false
-          is_custom=false
-          is_trunk_snapshot=false
-          
-          if [[ ${version} =~ ^[0-9]{1}.[0-9]{1}.[0-9]{1}-SNAPSHOT$ ]]; then
-            version=${build_id}
-            is_snapshot=true
-            if [[ "${is_trunk}" == 'true' ]]; then
-              is_trunk_snapshot=true
-            fi
-          elif [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}$ ]]; then
-            is_release=true
-            is_latest=true
-          elif [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts$ ]]; then
-            is_snapshot=true
-            version=${build_id}
-          elif [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts_v[0-9]{2}$ ]]; then
-            is_release=true
-          else
-            is_custom=true
-            version=${build_id}
-          fi
-          
-          if [[ "${{ inputs.force_snapshot }}" == 'true' ]]; then
-            is_snapshot=true
-            is_release=false
-            is_latest=false
-          fi
-          
-          echo "version=${version}"
-          echo "build_hash=${build_hash}"
-          echo "build_id=${build_id}"
-          echo "is_trunk=${is_trunk}"
-          echo "is_lts=${is_lts}"
-          echo "is_snapshot=${is_snapshot}"
-          echo "is_trunk_snapshot=${is_trunk_snapshot}"
-          echo "is_release=${is_release}"
-          echo "is_latest=${is_latest}"
-          echo "is_custom=${is_custom}"
-          
-          echo "version=${version}" >> $GITHUB_OUTPUT
-          echo "build_hash=${build_hash}" >> $GITHUB_OUTPUT
-          echo "build_id=${build_id}" >> $GITHUB_OUTPUT
-          echo "is_trunk=${is_trunk}" >> $GITHUB_OUTPUT
-          echo "is_lts=${is_lts}" >> $GITHUB_OUTPUT
-          echo "is_snapshot=${is_snapshot}" >> $GITHUB_OUTPUT
-          echo "is_trunk_snapshot=${is_trunk_snapshot}" >> $GITHUB_OUTPUT
-          echo "is_release=${is_release}" >> $GITHUB_OUTPUT
-          echo "is_latest=${is_latest}" >> $GITHUB_OUTPUT
-          echo "is_custom=${is_custom}" >> $GITHUB_OUTPUT
-        if: success()
+          type=raw,value={{sha}},enable=${{ steps.set-common-vars.outputs.is_custom
+          }}
 
-      - name: Docker.io login
-        uses: docker/login-action@v3.0.0
-        with:
-          username: ${{ secrets.docker_io_username }}
-          password: ${{ secrets.docker_io_token }}
-        if: inputs.docker_registry == 'DOCKER.IO' || inputs.docker_registry == 'BOTH'
+          '
+    - continue-on-error: true
+      if: success()
+      name: Debug Docker Metadata
+      run: 'echo "${{ fromJSON(steps.meta.outputs.json) }}"
 
-      - name: GHCR.io login
-        uses: docker/login-action@v3.0.0
-        with:
-          registry: ghcr.io
-          username: ${{ secrets.ghcr_io_username }}
-          password: ${{ secrets.ghcr_io_token }}
-        if: inputs.docker_registry == 'GHCR.IO' || inputs.docker_registry == 'BOTH'
+        '
+    - continue-on-error: true
+      if: success()
+      name: Set up QEMU
+      uses: docker/setup-qemu-action@v3.0.0
+      with:
+        image: tonistiigi/binfmt:latest
+        platforms: ${{ inputs.docker_platforms }}
+    - continue-on-error: true
+      id: docker-setup-buildx
+      if: success()
+      name: Docker Setup Buildx
+      uses: docker/setup-buildx-action@v3.0.0
+      with:
+        driver-opts: 'image=moby/buildkit:v0.12.2
 
-      - name: Docker Metadata
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: |
-            dotcms/dotcms
-          tags: |
-            type=raw,value=${{ steps.set-common-vars.outputs.version }}_{{sha}},enable=true
-            type=raw,value=${{ steps.set-common-vars.outputs.version }}_SNAPSHOT,enable=${{ steps.set-common-vars.outputs.is_snapshot }}
-            type=raw,value=${{ steps.set-common-vars.outputs.version }}_latest_SNAPSHOT,enable=${{ steps.set-common-vars.outputs.is_trunk_snapshot }}
-            type=raw,value=${{ steps.set-common-vars.outputs.version }},enable=${{ steps.set-common-vars.outputs.is_release }}
-            type=raw,value=latest,enable=${{ steps.set-common-vars.outputs.is_latest }}
-            type=raw,value={{sha}},enable=${{ steps.set-common-vars.outputs.is_custom }}
-        if: success()
+          '
+        platforms: ${{ inputs.docker_platforms }}
+        version: latest
+    - continue-on-error: true
+      if: success()
+      name: Build/Push Docker Image
+      uses: docker/build-push-action@v5
+      with:
+        cache-from: type=gha
+        cache-to: type=gha,mode=max
+        context: ${{ env.DOCKER_BUILD_CONTEXT }}/context
+        labels: ${{ steps.meta.outputs.labels }}
+        platforms: ${{ inputs.docker_platforms }}
+        pull: true
+        push: false
+        tags: ${{ steps.meta.outputs.tags }}
+    - continue-on-error: true
+      id: format-tags
+      name: Format Tags
+      run: 'tags=''''
 
-      - name: Debug Docker Metadata
-        run: |
-          echo "${{ fromJSON(steps.meta.outputs.json) }}"
-        if: success()
+        tags_arr=( ${{ steps.meta.outputs.tags }} )
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3.0.0
-        with:
-          image: tonistiigi/binfmt:latest
-          platforms: ${{ inputs.docker_platforms }}
-        if: success()
 
-      - name: Docker Setup Buildx
-        id: docker-setup-buildx
-        uses: docker/setup-buildx-action@v3.0.0
-        with:
-          version: latest
-          platforms: ${{ inputs.docker_platforms }}
-          driver-opts: |
-            image=moby/buildkit:v0.12.2
-        if: success()
+        for tag in "${tags_arr[@]}"
 
-      - name: Build/Push Docker Image
-        uses: docker/build-push-action@v5
-        with:
-          context: ${{ env.DOCKER_BUILD_CONTEXT }}/context
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          platforms: ${{ inputs.docker_platforms }}
-          pull: true
-          push: true
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-        if: success()
+        do
 
-      - name: Format Tags
-        id: format-tags
-        run: |
-          tags=''
-          tags_arr=( ${{ steps.meta.outputs.tags }} )
+        [[ -n "${tags}" ]] && tags="${tags}, "
 
-          for tag in "${tags_arr[@]}"
-          do
-          [[ -n "${tags}" ]] && tags="${tags}, "
-          tags="${tags}\`${tag}\`"
-          done
+        tags="${tags}\`${tag}\`"
 
-          echo "formatted_tags=${tags}" >> $GITHUB_OUTPUT
+        done
+
+
+        echo "formatted_tags=${tags}" >> $GITHUB_OUTPUT
+
+        '
+name: Maven Build Docker Image
+on:
+  repository_dispatch:
+    types: trigger-ga___maven-build-docker-image.yml
diff --git a/.github/workflows/publish-npm-package.yml b/.github/workflows/publish-npm-package.yml
--- a/.github/workflows/publish-npm-package.yml
+++ b/.github/workflows/publish-npm-package.yml
@@ -1,75 +1,48 @@
-name: 'Publish NPM Package'
-on:
-  workflow_call:
-    inputs:
-      ref:
-        description: 'Ref to checkout'
-        required: true
-        type: string
-      artifact-id:
-        description: 'Artifact id'
-        required: true
-        type: string
-      run-id:
-        description: 'Run id'
-        required: true
-        type: number
-      npm-package-version-tag:
-        description: 'NPM package version tag'
-        required: true
-        type: string
-    secrets:
-      gh-pat:
-        description: 'GitHub Personal Access Token'
-        required: true
-      npm-token:
-        description: 'NPM registry token'
-        required: false
-
 env:
   NODE_VERSION: 19
-
 jobs:
   publish-npm-package:
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     steps:
-      - name: 'Checkout'
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.ref }}
+    - continue-on-error: true
+      name: Checkout
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ inputs.ref }}
+    - continue-on-error: true
+      uses: ./.github/actions/cleanup-runner
+    - continue-on-error: true
+      name: Set up Node.js
+      uses: actions/setup-node@v4
+      with:
+        node-version: ${{ env.NODE_VERSION }}
+    - continue-on-error: true
+      name: Download all build artifacts
+      uses: actions/download-artifact@v4
+      with:
+        github-token: ${{ secrets.gh-pat }}
+        name: ${{ inputs.artifact-id }}
+        path: ${{ github.workspace }}/npm-package
+        run-id: ${{ inputs.run-id }}
+    - continue-on-error: true
+      name: Validate NPM package
+      run: "echo \"::group::NPM package contents\"\nif [ ! -f ${{ github.workspace\
+        \ }}/npm-package/package.json ]; then\n  echo \"::error::NPM package not found.\
+        \ Exiting...\"\n  exit 1\nelse\n  echo \"::notice::NPM package found. Proceeding...\"\
+        \n  cat ${{ github.workspace }}/npm-package/package.json\nfi\n"
+    - continue-on-error: true
+      env:
+        NPM_AUTH_TOKEN: ${{ secrets.npm-token }}
+        NPM_PACKAGE_VERSION_TAG: ${{ inputs.npm-package-version-tag }}
+      if: success()
+      name: Publish to NPM registry
+      run: 'echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
 
-      - uses: ./.github/actions/cleanup-runner
+        npm publish --access public --tag ${NPM_PACKAGE_VERSION_TAG}
 
-      - name: 'Set up Node.js'
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ env.NODE_VERSION }}
-
-      - name: 'Download all build artifacts'
-        uses: actions/download-artifact@v4
-        with:
-          path: ${{ github.workspace }}/npm-package
-          name: ${{ inputs.artifact-id }}
-          run-id: ${{ inputs.run-id }}
-          github-token: ${{ secrets.gh-pat }} # token with actions:read permissions on target repo
-
-      - name: 'Validate NPM package'
-        run: |
-          echo "::group::NPM package contents"
-          if [ ! -f ${{ github.workspace }}/npm-package/package.json ]; then
-            echo "::error::NPM package not found. Exiting..."
-            exit 1
-          else
-            echo "::notice::NPM package found. Proceeding..."
-            cat ${{ github.workspace }}/npm-package/package.json
-          fi
-
-      - name: 'Publish to NPM registry'
-        if: success()
-        working-directory: ${{ github.workspace }}/npm-package
-        env:
-          NPM_AUTH_TOKEN: ${{ secrets.npm-token }}
-          NPM_PACKAGE_VERSION_TAG: ${{ inputs.npm-package-version-tag }}
-        run: |
-          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
-          npm publish --access public --tag ${NPM_PACKAGE_VERSION_TAG}
+        '
+      working-directory: ${{ github.workspace }}/npm-package
+name: Publish NPM Package
+on:
+  repository_dispatch:
+    types: trigger-ga___publish-npm-package.yml
